[package]
name = "ps-alloc"
version = "0.1.0-6"
edition = "2021"
description = "a reasonably safe allocator"
license = "GPL-3.0-or-later"

[dependencies]
thiserror = "2.0.12"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
